server:
  port: 7000
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/ecommerce?useSSL=false&serverTimezone=UTC
    password: 

  jpa:
    properties:
      hibernate:
        ddl-auto: update
        show-sql: true
        open-in-view: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        dialect: org.hibernate.dialect.MySQLDialect
    packages-to-scan: 
      - "project.ip.ecommerce.entity"


